global using Application.Common.Interfaces;
global using Application.Common.Exceptions;
global using FluentValidation;
global using MediatR;
global using Domain.Entities;
global using Application.Common.Models;
global using AutoMapper;
global using Application.Common.Extensions;
global using Domain.Common.Events;